/*
 * generated by Xtext 2.37.0
 */
package org.xtext.example.mydsl;

import org.xtext.example.mydsl.scoping.AbstractMyDslScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyDslRuntimeModule extends AbstractMyDslRuntimeModule {
}
