grammar org.xtext.example.mydsl.MyDsl with org.eclipse.xtext.common.Terminals

generate myDsl "http://www.xtext.org/example/mydsl/MyDsl"

Config:
    (sections+=Section)*;

Section:
    name=ID ':' (entries+=Entry)*;

Entry:
    SimpleEntry | Block | ListEntry;

SimpleEntry:
    name=ID '->' value=Value;

Block:
    name=ID ':' (entries+=Entry)*;

ListEntry:
    '->' value=STRING;

Value:
    STRING | INT | Boolean;

Boolean:
    'true' | 'false';