/*
 * generated by Xtext 2.37.0
 */
package org.xtext.example.mydsl.validation;

import org.eclipse.xtext.validation.Check
import org.xtext.example.mydsl.myDsl.IntConstraint
import org.xtext.example.mydsl.myDsl.*;
import org.eclipse.xtext.EcoreUtil2
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference
import org.xtext.example.mydsl.myDsl.impl.StringConstraintImpl
import org.xtext.example.mydsl.myDsl.impl.IntConstraintImpl
import org.xtext.example.mydsl.myDsl.impl.BoolConstraintImpl
import org.xtext.example.mydsl.myDsl.impl.IPConstraintImpl

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class MyDslValidator extends AbstractMyDslValidator {
	
	public static final String INVALID_EXPRESSION_RESULT_TYPE = "invalidExpressionResultType";	
    protected enum Type {
        INT, STRING, BOOL, IP, UNKNOWN, ERROR
    }
    
    @Check
    def checkConstraintValueType(Constraint constraint) {
        var Expression valueExpression = null
        var Type expectedType = Type.UNKNOWN
        var EReference errorFeature = null

        switch constraint {
            IntConstraint: {
                valueExpression = constraint.value
                expectedType = Type.INT
                errorFeature = MyDslPackage.Literals.INT_CONSTRAINT__VALUE
            }
            StringConstraint: {
                valueExpression = constraint.value
                expectedType = Type.STRING
                errorFeature = MyDslPackage.Literals.STRING_CONSTRAINT__VALUE
            }
            BoolConstraint: {
                valueExpression = constraint.value
                expectedType = Type.BOOL
                errorFeature = MyDslPackage.Literals.BOOL_CONSTRAINT__VALUE
            }
            default: {
                // Ignore IPConstraint
                return
            }
        }

        if (valueExpression !== null) {
            var actualType = computeType(valueExpression)

            if (actualType == Type.ERROR) {
                error("Result of expression must be an " + expectedType.toString().toLowerCase(),
                    errorFeature,
                    INVALID_EXPRESSION_RESULT_TYPE)
            }
        }
    }
    
    def computeType(Expression exp) {
        switch exp {
            Plus: {
                val leftType = computeType(exp.left)
                val rightType = computeType(exp.right)
                if (leftType == Type.INT && rightType == Type.INT) {
                    return Type.INT
                }

                if (leftType == Type.STRING && rightType == Type.STRING) {
                    return Type.STRING
                }
                return Type.ERROR
            }
            Minus: {
                val leftType = computeType(exp.left)
                val rightType = computeType(exp.right)
                if (leftType == Type.INT && rightType == Type.INT) {
                    return Type.INT
                }
                return Type.ERROR
            }
            Mult: {
                val leftType = computeType(exp.left)
                val rightType = computeType(exp.right)
                if (leftType == Type.INT && rightType == Type.INT) {
                    return Type.INT
                }
                return Type.ERROR
            }
            Div: {
                val leftType = computeType(exp.left)
                val rightType = computeType(exp.right)
                if (leftType == Type.INT && rightType == Type.INT) {
                    return Type.INT
                }
                return Type.ERROR
            }
            Number: return Type.INT
            Str: return Type.STRING
            Bool: return Type.BOOL
            PropertyReference: {
                val referencedEntry = exp.ref
                
                if (referencedEntry !== null) {
                    val entryExp = referencedEntry

                    
                    if (entryExp instanceof IntConstraintImpl) {
                        return Type.INT
                    } else if (entryExp instanceof StringConstraintImpl) {
                        return Type.STRING
                    } else if (entryExp instanceof BoolConstraintImpl) {
                        return Type.BOOL
                    } else if (entryExp instanceof IPConstraintImpl) {
                        return Type.IP 
                    }
                }
            }
            default: return Type.UNKNOWN
        }
    }
}

/*
config Server
	property1: Int > 10 + 10
	property2: String = "hello"
	property3: Bool != false + 10
	property4: IP >127.0.0.1
	
	property5: Int > property1 + 10 + "testing" + false
 */
 
 
 
 