/*
 * generated by Xtext 2.37.0
 */
package org.xtext.example.mydsl.scoping;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.naming.QualifiedName;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.resource.EObjectDescription;
import org.eclipse.xtext.resource.IEObjectDescription;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;
import org.eclipse.xtext.scoping.impl.SimpleScope;
import org.xtext.example.mydsl.myDsl.Config;
import org.xtext.example.mydsl.myDsl.Entry;

public class MyDslScopeProvider extends AbstractDeclarativeScopeProvider {

	@Override
	public IScope getScope (EObject ctx, EReference ref) {
		Config config = getConfig(ctx);
		List<IEObjectDescription> descriptions = new ArrayList<>();
        
        for (Entry topEntry : config.getEntries()) {
            QualifiedName topName = QualifiedName.create(topEntry.getName());
            descriptions.add(EObjectDescription.create(topName, topEntry));

            addNestedDescriptions(topEntry, topEntry.getName(), descriptions);
        }
        
        return new SimpleScope(descriptions);
    }
	
    private void addNestedDescriptions(Entry parent, String qualifiedPrefix, List<IEObjectDescription> descriptions) {
        if (parent.getEntries() != null) {
            for (Entry child : parent.getEntries()) {
                String qualifiedNameStr = qualifiedPrefix + "." + child.getName();
                QualifiedName qualifiedName = QualifiedName.create(qualifiedNameStr.split("\\."));
                descriptions.add(EObjectDescription.create(qualifiedName, child));
                
                addNestedDescriptions(child, qualifiedNameStr, descriptions);
            }
        }
    }
	
	private Config getConfig(EObject ctx) {
		EObject current = ctx;
		
		while (current != null && !(current instanceof Config)) {
			current = current.eContainer();
		}
		return (Config) current;
	}
}
