/*
 * generated by Xtext 2.37.0
 */
package org.xtext.example.mydsl.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import org.eclipse.xtext.xbase.testing.CompilationTestHelper
import org.eclipse.xtext.xbase.lib.util.ReflectExtensions

@ExtendWith(InjectionExtension)
@InjectWith(MyDslInjectorProvider)
class MyDslGeneratorTest {
	@Inject extension CompilationTestHelper
	@Inject extension ReflectExtensions
	
	@Test
	def void checkTestConfigJsonStructure() {
		'''
config Server
	property1: String = "hello" + "world"
		'''.compile[
			val methods = getCompiledClass("ConfigTests.Server").methods
			
			val hasMethod = methods.exists[method | method.name == "testConfigJsonStructure"]
			
			Assertions.assertTrue(hasMethod)
		]
	}
	
	@Test
	def void checkMethodsCreated() {
		'''
config Server
	property1: String = "hello" + "world"
		'''.compile[
			val methods = getCompiledClass("ConfigTests.Server").methods
			
			val hasMethod = methods.exists[method | method.name == "testproperty1"]
			
			Assertions.assertTrue(hasMethod)
		]
	}
}
