/*
 * generated by Xtext 2.37.0
 */
package org.xtext.example.mydsl.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import org.xtext.example.mydsl.myDsl.Config
import org.eclipse.xtext.testing.validation.ValidationTestHelper
import org.xtext.example.mydsl.myDsl.MyDslPackage
import org.xtext.example.mydsl.myDsl.IntConstraint
import org.xtext.example.mydsl.myDsl.Div
import org.xtext.example.mydsl.validation.MyDslValidator
import org.xtext.example.mydsl.myDsl.StringConstraint
import org.xtext.example.mydsl.myDsl.Plus
import org.xtext.example.mydsl.myDsl.BoolConstraint

@ExtendWith(InjectionExtension)
@InjectWith(MyDslInjectorProvider)
class MyDslValidationTest {
	@Inject extension ParseHelper<Config> 
	@Inject extension ValidationTestHelper
	
	@Test
	def void incompatibleTypes() {
		val result = '''
			config Server
			property1: String = false + "hello"
		'''.parse

        val issues = result.validate
        val hasInvalidExpressionError = issues.exists[ it.code == MyDslValidator.INCOMPATIBLE_EXPRESSION_TYPES ]
        
        Assertions.assertTrue(hasInvalidExpressionError)
	}
	
	@Test
	def void incompatibleTypesOfReferencedPropertiesInExpressions() {
		val result = '''
			config Server
			property1: Int = 10
			property2: String = "hello" + property1
		'''.parse

        val issues = result.validate
        val hasInvalidExpressionError = issues.exists[ it.code == MyDslValidator.INCOMPATIBLE_EXPRESSION_TYPES ]
        
        Assertions.assertTrue(hasInvalidExpressionError)
	}
	
	@Test
	def void expressionDoesNotMatchConstraintType() {
		val result = '''
			config Server
			property1: Int = "hello" + "world"
		'''.parse

        val issues = result.validate
        val hasInvalidResultType = issues.exists[ it.code == MyDslValidator.INVALID_EXPRESSION_RESULT_TYPE ]
        
        Assertions.assertTrue(hasInvalidResultType)
	}
	
	@Test
	def void complexBooleanExpressionNotAllowed() {
		val result = '''
			config Server
			property1: Bool = true + false
		'''.parse

        val issues = result.validate
        val hasComplexBoolExpressionError = issues.exists[ it.code == MyDslValidator.COMPLEX_BOOLEAN_EXPRESSION_ERROR ]
        
        Assertions.assertTrue(hasComplexBoolExpressionError)
	}
	
	@Test
	def void multiplicativeExpressionOnlyAllowedForIntegers() {
		val result = '''
			config Server
			property1: String = "hello" * "world"
		'''.parse	
        
        val issues = result.validate
        val hasMultError = issues.exists[ it.code == MyDslValidator.MULTIPLICATVIE_EXPRESSION_ERROR ]
        
        Assertions.assertTrue(hasMultError)
	}

	@Test
	def void subtractionOperatorError() {
		val result = '''
			config Server
			property1: String = "hello" - "world"
		'''.parse	
        
        val issues = result.validate
        val hasMultError = issues.exists[ it.code == MyDslValidator.SUBTRACTION_OPERATOR_ERROR ]
        
        Assertions.assertTrue(hasMultError)
	}
	
	@Test
	def void divionByZero() {
		val result = '''
			config Server
			property1: Int = 10 / 0
		'''.parse

        val issues = result.validate
        val hasDivisionByZeroError = issues.exists[ it.code == MyDslValidator.DIVISION_BY_ZERO_ERROR ]
        
        Assertions.assertTrue(hasDivisionByZeroError)
	}
}
